package com.morlabs.Exceptions;

public class TestK {

	public static void main(String[] args) {

	static int test() 
	{   try 
	{    } 
	catch(NumberFormatException ex) 
	{ 
		return 20;  
		}  
	finally
		
		
		 catch(ArithmeticException e)
	{   
			 System.out.println("task1 is completed");
			 } 
	catch(ArrayIndexOutOfBoundsException e)
	{      
		System.out.println("task 2 completed");
		}  
	System.out.println("rest of the code...");   
	}
}

}
